### Ceci est un projet Bancaire qui consiste a analysé les données des clients d'une Banque et determiné si un client  peut beneficier d'un pret ou non

## Les étapes du projets:

### 1. Comprendre la problematique(Le probleme metier : A Quel type de client peut on accorder un credit ?)
### 2. Collecte de données
### 3. Netoyage des données
### 4. Analyse exploratoire(Visualisation)
### 5. Préparation du modele(Modele du machine learning)
### 6. Evaluer les performances du modele
### 7. Deploiement du modele

In [38]:
import pandas as pd             # Pour la manipulation des données
import numpy as np              # Pour les calculs numériques
import matplotlib.pyplot as plt # Pour la visualisation des données
import seaborn as sns           # Pour la visualisation avancée des données
import pickle                   # Pour la sérialisation des objets Python(utilsé pour generer le model qui sera intégré a lappli)
                                # La sérialisation consiste à transformer un objet Python en données que l'on peut enregistrer

In [39]:
from google.colab import drive
import os

### Connection a google drive pour utilisé les fichier

In [40]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [41]:

print(os.listdir('/content/drive/MyDrive/DataScienceProject'))

['test_Y3wMUE5_7gLdaTN.csv', 'train_u6lujuX_CVtuZ9i.csv']

### Charger les données dans une variable local: data

In [42]:
df = pd.read_csv('/content/drive/MyDrive/DataScienceProject/train_u6lujuX_CVtuZ9i.csv')

In [43]:
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

## Comprehesion des colonne:

#### ==> Loan_ID: l'identifiant de chaque client
#### ==> Gender : Le genre du demandeur: Masculin ou feminin
#### ==> Married : Situation matrimonial du demandeur: Marié ou celibatire	
#### ==> Dependents : Nombre Personne a charge du demandeur : 0, 1, 2 ou 3 etc...
#### ==> Education : Niveau d'etude du demandeur: Diplomé ou non diplomé
#### ==> Self_Employed : Le demandeur est il un travailleur independant ou dependant
#### ==> ApplicantIncome : Revenu du candidant ou client voulant le pret
#### ==> CoapplicantIncome : Revenu du co-demandeur : Epoux si c'est une femme, epouse si c'est un homme
#### ==> LoanAmount : Montant du pret
#### ==> Loan_Amount_Term: Durée du rembourssement du pret(Exemple: la valeur 360.0 signifie que le pret doit etre rembourser durant 360 mois soit 30 ans)
#### ==> Credit_History  : Historique des credit du demandeur( 1 si la personne a eu u bon historique et 0 si non)
#### ==> Property_Area   : représente la zone géographique dans laquelle se trouve le bien immobilier concerné par le prêt(rural,urbaine,semiurrbaine etc..)--> Nb: Dans ce projet le prêt est bien une somme d'argent, mais il s'agit plus précisément d'un prêt immobilier ou d'un prêt destiné à financer un bien immobilier.
#### ==> Loan_Status     : status du pret (: validé, N:refusé)

### Afficher toute la base données

In [47]:
# pd.set_option('display.max_rows', df.shape[0]) # Affiche toutes les lignes du DataFrame
# df

In [ ]:
pd.set_option('display.max_rows', 10) # Affiche les premieres et dernieres lignes du DataFrame
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

### Verification des valeurs manquantes

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

### Afficher les valeurs manquantes pour chaque colonne, triées par ordre décroissant

In [49]:
df.isnull().sum().sort_values(ascending=False)

Credit_History       50
Self_Employed        32
LoanAmount           22
Dependents           15
Loan_Amount_Term     14
                     ..
Loan_ID               0
CoapplicantIncome     0
ApplicantIncome       0
Property_Area         0
Loan_Status           0
Length: 13, dtype: int64

### Statistique descriptive des données

In [50]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

### Au cas ou on trouvait par exemple pour ApplicantIncome	une valeur minimal -4 et une valeur maximale: 81000.000000 alors yaurait un probleme